### ISSUE TITLE
Feature request: Download only when sponsorblock available and/or redownload

### ISSUE THREAD

**Issue by ext4xfs** [ikoyhn/go-podcast-sponsor-block#5]
looks like this project is extremely similar to https://github.com/ericmedina024/podcast-sponsor-block. From what I can see this project is likely to have the same issue:

Since the podcast is only downloaded once, if you download a podcast right after it is released it won't have sponsorblock data. https://github.com/kieraneglin/pinchflat redownloads the video based on config. It would be nice to have something similar.

As an aside, most podcasts on youtube don't have sponsorblock information, only the really large ones like joe rogan. There are some ML models that could address this, however in my testing they were far from perfect. Just something to think about.

**Comment by ikoyhn** [comment]
You're correct, this is basically my version of Eric's implementation! Good points on the sponsor block missing. I've been thinking about possible solutions to that and what I was thinking of doing was hitting the sponsor block api endpoint to get the length of the video with the most up to date segments removed, and if there is a difference between that and the downloaded file then redownload it before serving. I also am working on cron jobs to auto cleanup files after they haven't been accessed in a while. I'll take a look at the other repo you mentioned to see if there's any inspiration I can take from it!

ML is also an interesting idea... Might look into that after I get all other things wrapped up and working perfect!

-Jared

**Comment by ikoyhn** [comment]
Added in the sponsorblock check when the episode is first requested/download to get the total time of sponsor segments. If the user requests that episode again it will do a similar check and if there are any new sponsor segments it will redownload that file. Currently I have a small buffer of 2 seconds so that if the total time of skipped sponsor segments between what is downloaded and what is most up to date is under 2 seconds it wont redownload, figured that may save some bandwidth in case sponsor segments get altered by a second or so and im not sure its worth a redownload to save only 2 seconds or less. May also look to add a docker var that can be set so that it only downloads the file when at least one sponsor segment is available for the episode in the future.

**Comment by ext4xfs** [comment]
awesome, will try it out thank you
